### ISSUE TITLE
Unable to run python scripts (ghidra exporter)

### ISSUE THREAD

**Issue by martmists-gh** [NyaMisty/docker-wine-ida#5]
```py
Z:\files\idaxml.py: Missing parentheses in call to 'print'. Did you mean print(msg)? (Z:/files/idaxml.py, line 2640)
Traceback (most recent call last):
  File "C:\IDA\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), path, 'exec')
  File "Z:/files/idaxml.py", line 2640
    print msg
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?
```

**Comment by Manouchehri** [comment]
This is because you're using a Python 2 script, but this repo installs Python 3.

**Comment by Manouchehri** [comment]
Also, Python 2 will not be supported at all as of IDA Pro 7.8.

https://hex-rays.com/blog/future-idapython-versions-will-be-python3-only/

**Comment by Martmists-GH** [comment]
Looks like Ghidra's scripts were python 2, and a PR exists to make them compatible with python 3 https://github.com/NationalSecurityAgency/ghidra/pull/1618
