### ISSUE TITLE
The terminal reports an error, but double-clicking ida.exe is normal

### ISSUE THREAD

**Issue by 1amfine2333** [NyaMisty/docker-wine-ida#6]
nyamisty/docker-wine-ida:7.6sp1
```wine C:\\IDA\\ida.exe``` error
![image](https://user-images.githubusercontent.com/24676292/151905732-2ee483bb-aa15-4a02-8bc9-838968868418.png)
but  double-clicking ```/root/host/var/lib/docker/overlay2/a783e5ab34a55b97e3fd47d179c2f778a6ff8fc91d3c887755959b05506fd201/diff/root/.wine/drive_c/IDA/ida.exe``` is normal
![image](https://user-images.githubusercontent.com/24676292/151908279-6092421e-f494-4669-892a-d65ac9269a9f.png)

**Comment by NyaMisty** [comment]
My fault, now fixed!

**Comment by 1amfine2333** [comment]
> My fault, now fixed

Ok, thank you, can you add WeChat or other ways of contact ?
![image](https://user-images.githubusercontent.com/24676292/152069423-866b3302-2277-4123-960b-88a4de0dab24.jpeg)

**Comment by NyaMisty** [comment]
OFC, contact tg @MistyNya
