### ISSUE TITLE
Prebuilt containers are gone

### ISSUE THREAD

**Issue by not-matthias** [NyaMisty/docker-wine-ida#9]

**Comment by NyaMisty** [comment]
Thanks for letting me know!
Seems that DockerHub is not happy with my image, and they pulled it off WITHOUT EVEN NOTICE ME.
I'll try to post docker image elsewhere :(

**Comment by not-matthias** [comment]
Thank you!

**Comment by NyaMisty** [comment]
I know. Thanks for your advice :)
And I've transferred it into ghcr.io
